import sys
import os
sys.path.insert(0, os.path.dirname(os.path.dirname(os.path.abspath(__file__))))

from typing import TypedDict, Annotated
import operator
from state import Finding, TestResults, take_last


class AgentSpec(TypedDict):
    """Specification for a dynamically spawned sub-agent."""
    name: str               # e.g., "security_deep", "performance_focused"
    role: str               # one-line role description
    system_prompt: str       # generated by the orchestrator
    tools: list[dict]        # selected subset of available tools
    focus_areas: list[str]   # what to look for specifically in this code
    depth: str               # "shallow" (single pass) or "deep" (can spawn sub-agents)


class SubAgentResult(TypedDict):
    """Result from a dynamically spawned sub-agent."""
    agent_name: str
    findings: list[Finding]
    input_tokens: int
    cache_tokens: int


class DeepReviewState(TypedDict):
    # input
    code_input: str

    # orchestrator plan — the supervisor generates this dynamically
    agent_plan: Annotated[list[AgentSpec] | None, take_last]
    plan_reasoning: Annotated[str | None, take_last]

    # dynamic agent execution (Send handles dispatch — no queue needed)
    sub_agent_results: Annotated[list[SubAgentResult], operator.add]

    # review layer output (same as v1 — accumulated from sub-agents)
    findings: Annotated[list[Finding], operator.add]

    # fixer layer (reused from v1 pattern)
    current_code: str | None
    fixed_issues: list[Finding] | None
    iteration: int
    test_results: TestResults | None

    # deep fixer — reflection
    fix_critique: Annotated[str | None, take_last]
    fix_approved: Annotated[bool | None, take_last]

    # output
    final_report: str | None

    # cache enforcement (reused from v1)
    cached_prefix: Annotated[dict | None, take_last]
    tool_results: Annotated[list[dict] | None, take_last]
    tool_definitions_snapshot: list[dict] | None
    current_tool_definitions: list[dict] | None

    # control flow
    violation_detected: bool
    violation_type: str | None
    next_node: Annotated[str | None, take_last]
    user_message: Annotated[str | None, take_last]
    previous_fixed_count: int
    retry_count: int
    error: str | None
